main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,8 +18,12 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          if [ -f requirements.txt ]; 
+          then pip install -r requirements.txt; 
+          fi
 
       - name: Run script
         run: |
-          if [ -f hello.py ]; then python hello.py; else echo "hello.py not found"; exit 1; fi
+          if [ -f hello.py ]; then python hello.py; else echo "hello.py not found"; 
+          exit 1; 
+          fi
